# Generated by Django 4.0.3 on 2022-04-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=200)),
                (
                    "company_name",
                    models.CharField(max_length=200, null=True, blank=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="events.conference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "attendee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="badge",
                        serialize=False,
                        to="attendees.attendee",
                    ),
                ),
            ],
        ),
    ]
